name: copy schema
on: [push]
jobs:
  build:
    name: Copy Schema
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.SSH2 }}
        passphrase: ${{ secrets.DEPLOY_PASSWORD }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "documentation/Development/Schema/*"
        target: "~/CodeToSurvive/Schema"